/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API admin settings */
        get: operations["get-api-admin-settings"];
        /** Put API admin settings */
        put: operations["put-api-admin-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API admin users */
        get: operations["get-api-admin-users"];
        put?: never;
        /** Post API admin users */
        post: operations["post-api-admin-users"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API auth login */
        post: operations["post-api-auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API auth logout */
        post: operations["post-api-auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API auth me */
        get: operations["get-api-auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API push by token */
        get: operations["get-api-push-by-token"];
        put?: never;
        /** Post API push by token */
        post: operations["post-api-push-by-token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API setup */
        get: operations["get-api-setup"];
        put?: never;
        /** Post API setup */
        post: operations["post-api-setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams */
        get: operations["get-api-teams"];
        put?: never;
        /** Post API teams */
        post: operations["post-api-teams"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID alerts */
        get: operations["get-api-teams-by-team-id-alerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/alerts/{alertID}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API teams by team ID alerts by alert ID acknowledge */
        post: operations["post-api-teams-by-team-id-alerts-by-alert-id-acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID audit */
        get: operations["get-api-teams-by-team-id-audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID channels */
        get: operations["get-api-teams-by-team-id-channels"];
        put?: never;
        /** Post API teams by team ID channels */
        post: operations["post-api-teams-by-team-id-channels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/channels/{channelID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID channels by channel ID */
        get: operations["get-api-teams-by-team-id-channels-by-channel-id"];
        /** Put API teams by team ID channels by channel ID */
        put: operations["put-api-teams-by-team-id-channels-by-channel-id"];
        post?: never;
        /** Delete API teams by team ID channels by channel ID */
        delete: operations["delete-api-teams-by-team-id-channels-by-channel-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/channels/{channelID}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API teams by team ID channels by channel ID test */
        post: operations["post-api-teams-by-team-id-channels-by-channel-id-test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/escalation-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID escalation policies */
        get: operations["get-api-teams-by-team-id-escalation-policies"];
        put?: never;
        /** Post API teams by team ID escalation policies */
        post: operations["post-api-teams-by-team-id-escalation-policies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/escalation-policies/{policyID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID escalation policies by policy ID */
        get: operations["get-api-teams-by-team-id-escalation-policies-by-policy-id"];
        /** Put API teams by team ID escalation policies by policy ID */
        put: operations["put-api-teams-by-team-id-escalation-policies-by-policy-id"];
        post?: never;
        /** Delete API teams by team ID escalation policies by policy ID */
        delete: operations["delete-api-teams-by-team-id-escalation-policies-by-policy-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream team events
         * @description Server-Sent Events: `monitor` (state transitions), `alert` (alert changes) and `monitors_changed` (monitor created, updated or deleted). Steady-state checks are not streamed.
         */
        get: operations["stream-team-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/maintenance-windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID maintenance windows */
        get: operations["get-api-teams-by-team-id-maintenance-windows"];
        put?: never;
        /** Post API teams by team ID maintenance windows */
        post: operations["post-api-teams-by-team-id-maintenance-windows"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/maintenance-windows/{windowID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID maintenance windows by window ID */
        get: operations["get-api-teams-by-team-id-maintenance-windows-by-window-id"];
        /** Put API teams by team ID maintenance windows by window ID */
        put: operations["put-api-teams-by-team-id-maintenance-windows-by-window-id"];
        post?: never;
        /** Delete API teams by team ID maintenance windows by window ID */
        delete: operations["delete-api-teams-by-team-id-maintenance-windows-by-window-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID members */
        get: operations["get-api-teams-by-team-id-members"];
        put?: never;
        /** Post API teams by team ID members */
        post: operations["post-api-teams-by-team-id-members"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/members/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put API teams by team ID members by user ID */
        put: operations["put-api-teams-by-team-id-members-by-user-id"];
        post?: never;
        /** Delete API teams by team ID members by user ID */
        delete: operations["delete-api-teams-by-team-id-members-by-user-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/monitor-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID monitor overview */
        get: operations["get-api-teams-by-team-id-monitor-overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID monitors */
        get: operations["get-api-teams-by-team-id-monitors"];
        put?: never;
        /** Post API teams by team ID monitors */
        post: operations["post-api-teams-by-team-id-monitors"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/monitors/{monitorID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID monitors by monitor ID */
        get: operations["get-api-teams-by-team-id-monitors-by-monitor-id"];
        /** Put API teams by team ID monitors by monitor ID */
        put: operations["put-api-teams-by-team-id-monitors-by-monitor-id"];
        post?: never;
        /** Delete API teams by team ID monitors by monitor ID */
        delete: operations["delete-api-teams-by-team-id-monitors-by-monitor-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/monitors/{monitorID}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID monitors by monitor ID events */
        get: operations["get-api-teams-by-team-id-monitors-by-monitor-id-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/monitors/{monitorID}/heartbeats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID monitors by monitor ID heartbeats */
        get: operations["get-api-teams-by-team-id-monitors-by-monitor-id-heartbeats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/monitors/{monitorID}/uptime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID monitors by monitor ID uptime */
        get: operations["get-api-teams-by-team-id-monitors-by-monitor-id-uptime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/monitors/{monitorID}/uptime-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID monitors by monitor ID uptime summary */
        get: operations["get-api-teams-by-team-id-monitors-by-monitor-id-uptime-summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/notification-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID notification log */
        get: operations["get-api-teams-by-team-id-notification-log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API teams by team ID tokens */
        get: operations["get-api-teams-by-team-id-tokens"];
        put?: never;
        /** Post API teams by team ID tokens */
        post: operations["post-api-teams-by-team-id-tokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamID}/tokens/{tokenID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete API teams by team ID tokens by token ID */
        delete: operations["delete-api-teams-by-team-id-tokens-by-token-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddMemberInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/AddMemberInputBody.json
             */
            readonly $schema?: string;
            email: string;
            /** @enum {string} */
            role: "owner" | "editor" | "viewer";
        };
        AdminUserBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/AdminUserBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            email: string;
            /** Format: int64 */
            id: number;
            is_admin: boolean;
            name: string;
        };
        AlertBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/AlertBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            ack_source: "web" | "slack" | "telegram";
            acked: boolean;
            /** Format: date-time */
            acked_at: string | null;
            acked_by_name: string;
            /** Format: int64 */
            acked_by_user_id: number | null;
            flapping: boolean;
            id: string;
            /** Format: date-time */
            incident_start: string;
            message: string;
            /** Format: int64 */
            monitor_id: number;
            /** Format: date-time */
            next_escalation_at: string | null;
            notified_channel_ids: number[] | null;
            /** Format: date-time */
            opened_at: string;
            resolution: string;
            /** Format: date-time */
            resolved_at: string | null;
            /** Format: int64 */
            step: number;
            suppressed: boolean;
            /** Format: int64 */
            team_id: number;
            /** Format: date-time */
            updated_at: string;
        };
        AuditEntryBody: {
            action: string;
            /** Format: int64 */
            actor_token_id: number | null;
            /** Format: int64 */
            actor_user_id: number | null;
            /** Format: date-time */
            at: string;
            details: unknown;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            target_id: number | null;
            target_type: string;
            /** Format: int64 */
            team_id: number | null;
        };
        ChannelBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ChannelBody.json
             */
            readonly $schema?: string;
            config: unknown;
            config_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            is_default: boolean;
            name: string;
            /** Format: int64 */
            team_id: number;
            /** @enum {string} */
            type: "telegram" | "discord" | "slack" | "slack_app" | "smtp" | "webhook";
            /** Format: date-time */
            updated_at: string;
        };
        ChannelRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ChannelRequestBody.json
             */
            readonly $schema?: string;
            config: unknown;
            is_default?: boolean;
            name: string;
            /** @enum {string} */
            type: "telegram" | "discord" | "slack" | "slack_app" | "smtp" | "webhook";
        };
        CreateAdminUserInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/CreateAdminUserInputBody.json
             */
            readonly $schema?: string;
            email: string;
            is_admin: boolean;
            name: string;
            password: string;
        };
        CreateTeamInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/CreateTeamInputBody.json
             */
            readonly $schema?: string;
            name: string;
        };
        CreateTokenInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/CreateTokenInputBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            expires_at?: string;
            name: string;
            /** @enum {string} */
            scope: "read" | "write";
        };
        CreateTokenOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/CreateTokenOutputBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: int64 */
            id: number;
            name: string;
            /** @enum {string} */
            scope: "read" | "write";
            token: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        EscalationStepBody: {
            channel_ids: number[] | null;
            /**
             * Format: int64
             * @default 600
             */
            delay_s: number;
        };
        HeartbeatBody: {
            /** Format: int32 */
            latency_ms: number;
            message: string;
            /** Format: int64 */
            probe_id: number;
            /** @enum {string} */
            status: "down" | "up" | "pending" | "maintenance";
            /** Format: date-time */
            time: string;
        };
        ListAdminUsersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListAdminUsersOutputBody.json
             */
            readonly $schema?: string;
            users: components["schemas"]["AdminUserBody"][] | null;
        };
        ListAlertsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListAlertsOutputBody.json
             */
            readonly $schema?: string;
            alerts: components["schemas"]["AlertBody"][] | null;
        };
        ListAuditOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListAuditOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["AuditEntryBody"][] | null;
        };
        ListChannelsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListChannelsOutputBody.json
             */
            readonly $schema?: string;
            channels: components["schemas"]["ChannelBody"][] | null;
        };
        ListHeartbeatsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListHeartbeatsOutputBody.json
             */
            readonly $schema?: string;
            heartbeats: components["schemas"]["HeartbeatBody"][] | null;
        };
        ListMaintenanceWindowsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListMaintenanceWindowsOutputBody.json
             */
            readonly $schema?: string;
            maintenance_windows: components["schemas"]["MaintenanceWindowBody"][] | null;
        };
        ListMembersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListMembersOutputBody.json
             */
            readonly $schema?: string;
            members: components["schemas"]["MemberBody"][] | null;
        };
        ListMonitorsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListMonitorsOutputBody.json
             */
            readonly $schema?: string;
            monitors: components["schemas"]["MonitorBody"][] | null;
        };
        ListNotificationLogOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListNotificationLogOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["NotificationLogEntryBody"][] | null;
        };
        ListPoliciesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListPoliciesOutputBody.json
             */
            readonly $schema?: string;
            escalation_policies: components["schemas"]["PolicyBody"][] | null;
        };
        ListTeamsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListTeamsOutputBody.json
             */
            readonly $schema?: string;
            teams: components["schemas"]["TeamBody"][] | null;
        };
        ListTokensOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ListTokensOutputBody.json
             */
            readonly $schema?: string;
            tokens: components["schemas"]["TokenBody"][] | null;
        };
        LoginInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/LoginInputBody.json
             */
            readonly $schema?: string;
            email: string;
            password: string;
        };
        MaintenanceWindowBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/MaintenanceWindowBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: int64 */
            id: number;
            monitor_ids: number[] | null;
            name: string;
            /** @enum {string} */
            recurrence: "none" | "daily" | "weekly";
            /** Format: date-time */
            starts_at: string;
            /** Format: int64 */
            team_id: number;
            /** Format: date-time */
            updated_at: string;
        };
        MaintenanceWindowRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/MaintenanceWindowRequestBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            ends_at: string;
            monitor_ids: number[] | null;
            name: string;
            /**
             * @default none
             * @enum {string}
             */
            recurrence: "none" | "daily" | "weekly";
            /** Format: date-time */
            starts_at: string;
        };
        MeBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/MeBody.json
             */
            readonly $schema?: string;
            csrf_token: string;
            teams: components["schemas"]["MeTeam"][] | null;
            user: components["schemas"]["MeUser"];
        };
        MeTeam: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @enum {string} */
            role: "owner" | "editor" | "viewer";
        };
        MeUser: {
            email: string;
            /** Format: int64 */
            id: number;
            is_admin: boolean;
            name: string;
        };
        MemberBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/MemberBody.json
             */
            readonly $schema?: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "editor" | "viewer";
            /** Format: int64 */
            user_id: number;
        };
        MonitorBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/MonitorBody.json
             */
            readonly $schema?: string;
            channel_ids: number[] | null;
            config: unknown;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            escalation_policy_id: number | null;
            group_name: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            interval_s: number;
            name: string;
            /** Format: int64 */
            parent_id: number | null;
            paused: boolean;
            push_url?: string;
            /** Format: int64 */
            retries: number;
            /** Format: int64 */
            retry_interval_s: number;
            state: components["schemas"]["MonitorStateBody"];
            tags: string[] | null;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            timeout_s: number;
            /** @enum {string} */
            type: "http" | "keyword" | "tcp" | "ping" | "dns" | "push";
            /** Format: date-time */
            updated_at: string;
        };
        MonitorOverviewItem: {
            /** @description Most recent heartbeats, oldest first. */
            heartbeats: components["schemas"]["HeartbeatBody"][] | null;
            /** Format: int64 */
            monitor_id: number;
            /**
             * Format: double
             * @description Percent of non-maintenance checks up (or pending) in the last 24 hours; null without data.
             */
            uptime_24h: number | null;
            /**
             * Format: double
             * @description Percent from the daily rollups of the last 30 calendar days; null without data.
             */
            uptime_30d: number | null;
        };
        MonitorOverviewOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/MonitorOverviewOutputBody.json
             */
            readonly $schema?: string;
            monitors: components["schemas"]["MonitorOverviewItem"][] | null;
        };
        MonitorRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/MonitorRequestBody.json
             */
            readonly $schema?: string;
            channel_ids?: number[] | null;
            config: unknown;
            /** Format: int64 */
            escalation_policy_id?: number;
            group_name?: string;
            /**
             * Format: int64
             * @default 60
             */
            interval_s: number;
            name: string;
            /** Format: int64 */
            parent_id?: number;
            paused?: boolean;
            /**
             * Format: int64
             * @default 1
             */
            retries: number;
            /**
             * Format: int64
             * @default 20
             */
            retry_interval_s: number;
            tags?: string[] | null;
            /**
             * Format: int64
             * @default 10
             */
            timeout_s: number;
            /** @enum {string} */
            type: "http" | "keyword" | "tcp" | "ping" | "dns" | "push";
        };
        MonitorStateBody: {
            /** Format: int64 */
            consecutive_failures: number;
            /** Format: int64 */
            flap_count: number;
            /** Format: date-time */
            last_check_at: string;
            /** Format: date-time */
            since: string;
            /** @enum {string} */
            status: "down" | "up" | "pending" | "maintenance";
            /** Format: date-time */
            tls_expires_at: string | null;
        };
        NotificationLogEntryBody: {
            alert_id: string | null;
            /** Format: date-time */
            at: string;
            /** Format: int64 */
            attempt: number;
            /** Format: int64 */
            channel_id: number | null;
            dedupe_key: string;
            error: string;
            /** @enum {string} */
            event: "down" | "recovered" | "flapping" | "cert_expiry" | "test";
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            monitor_id: number | null;
            ok: boolean;
            /** Format: int64 */
            team_id: number;
        };
        PolicyBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/PolicyBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            name: string;
            steps: components["schemas"]["EscalationStepBody"][] | null;
            /** Format: int64 */
            team_id: number;
            /** Format: date-time */
            updated_at: string;
        };
        PolicyRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/PolicyRequestBody.json
             */
            readonly $schema?: string;
            name: string;
            steps: components["schemas"]["EscalationStepBody"][] | null;
        };
        PushOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/PushOutputBody.json
             */
            readonly $schema?: string;
            ok: boolean;
        };
        SettingsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/SettingsBody.json
             */
            readonly $schema?: string;
            block_private_targets: boolean;
            /** Format: int64 */
            retention_days: number | null;
        };
        SetupInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/SetupInputBody.json
             */
            readonly $schema?: string;
            email: string;
            name: string;
            password: string;
            team_name: string;
        };
        SetupStatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/SetupStatusOutputBody.json
             */
            readonly $schema?: string;
            needed: boolean;
        };
        StatusEventBody: {
            message: string;
            /**
             * @description Null for the oldest retained heartbeat.
             * @enum {string|null}
             */
            previous_status: "down" | "up" | "pending" | "maintenance" | null;
            /** @enum {string} */
            status: "down" | "up" | "pending" | "maintenance";
            /** Format: date-time */
            time: string;
        };
        StatusEventsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/StatusEventsOutputBody.json
             */
            readonly $schema?: string;
            events: components["schemas"]["StatusEventBody"][] | null;
        };
        TeamBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/TeamBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** @enum {string} */
            role: "owner" | "editor" | "viewer";
        };
        TestSendChannelOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/TestSendChannelOutputBody.json
             */
            readonly $schema?: string;
            ok: boolean;
        };
        TokenBody: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            last_used_at: string | null;
            name: string;
            /** @enum {string} */
            scope: "read" | "write";
        };
        UpdateMemberInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/UpdateMemberInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            role: "owner" | "editor" | "viewer";
        };
        UpdateSettingsInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/UpdateSettingsInputBody.json
             */
            readonly $schema?: string;
            block_private_targets: boolean;
            /** Format: int64 */
            retention_days?: number;
        };
        UptimeDayBody: {
            /** Format: int64 */
            avg_latency_ms: number;
            /** Format: int64 */
            checks: number;
            /** Format: date-time */
            day: string;
            /** Format: int64 */
            p95_latency_ms: number;
            /** Format: int64 */
            up: number;
        };
        UptimeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/UptimeOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            checks: number;
            days: components["schemas"]["UptimeDayBody"][] | null;
            /** Format: double */
            percentage: number | null;
            /** Format: int64 */
            up: number;
        };
        UptimeSummaryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/UptimeSummaryOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: double
             * @description From raw heartbeats; exact.
             */
            uptime_24h: number | null;
            /**
             * Format: double
             * @description From daily rollups (lags by up to one rollup interval).
             */
            uptime_30d: number | null;
            /**
             * Format: double
             * @description From daily rollups (lags by up to one rollup interval).
             */
            uptime_7d: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-api-admin-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-admin-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-admin-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAdminUsersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-admin-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminUserInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                upsera_session?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-push-by-token": {
        parameters: {
            query?: {
                status?: "up" | "down";
                msg?: string;
                ping?: number;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-push-by-token": {
        parameters: {
            query?: {
                status?: "up" | "down";
                msg?: string;
                ping?: number;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTeamsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-alerts": {
        parameters: {
            query?: {
                state?: "open" | "resolved" | "all";
                monitor_id?: number;
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAlertsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams-by-team-id-alerts-by-alert-id-acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                alertID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-audit": {
        parameters: {
            query?: {
                before?: number;
                limit?: number;
            };
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAuditOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-channels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListChannelsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams-by-team-id-channels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelRequestBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-channels-by-channel-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                channelID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-teams-by-team-id-channels-by-channel-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                channelID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-teams-by-team-id-channels-by-channel-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                channelID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams-by-team-id-channels-by-channel-id-test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                channelID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSendChannelOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-escalation-policies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPoliciesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams-by-team-id-escalation-policies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyRequestBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-escalation-policies-by-policy-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                policyID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-teams-by-team-id-escalation-policies-by-policy-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                policyID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-teams-by-team-id-escalation-policies-by-policy-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                policyID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "stream-team-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of monitor, alert and monitors_changed events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-maintenance-windows": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMaintenanceWindowsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams-by-team-id-maintenance-windows": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceWindowRequestBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceWindowBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-maintenance-windows-by-window-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                windowID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceWindowBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-teams-by-team-id-maintenance-windows-by-window-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                windowID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceWindowRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceWindowBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-teams-by-team-id-maintenance-windows-by-window-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                windowID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMembersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams-by-team-id-members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-teams-by-team-id-members-by-user-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                userID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-teams-by-team-id-members-by-user-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                userID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-monitor-overview": {
        parameters: {
            query?: {
                beats?: number;
            };
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorOverviewOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-monitors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMonitorsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams-by-team-id-monitors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorRequestBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-monitors-by-monitor-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                monitorID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-teams-by-team-id-monitors-by-monitor-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                monitorID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-teams-by-team-id-monitors-by-monitor-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                monitorID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-monitors-by-monitor-id-events": {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                teamID: number;
                monitorID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusEventsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-monitors-by-monitor-id-heartbeats": {
        parameters: {
            query?: {
                limit?: number;
                since?: string;
            };
            header?: never;
            path: {
                teamID: number;
                monitorID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListHeartbeatsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-monitors-by-monitor-id-uptime": {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                teamID: number;
                monitorID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UptimeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-monitors-by-monitor-id-uptime-summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                monitorID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UptimeSummaryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-notification-log": {
        parameters: {
            query?: {
                before_id?: number;
                limit?: number;
            };
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListNotificationLogOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-teams-by-team-id-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTokensOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-teams-by-team-id-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTokenOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-teams-by-team-id-tokens-by-token-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamID: number;
                tokenID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
